version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Build abyss
          working_directory: './Code/abyss/'
          command: 'mvn clean package'