version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Download javaws
          working_directory: '.'
          command: 'wget https://momoperes.ca/maven/abyss/javaws.jar'

      - run:
          name: Copy javaws
          working_directory: '.'
          command: 'chmod 755 javaws.jar && sudo cp javaws.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/javaws.jar'

      - run:
          name: Build abyss
          working_directory: './Code/abyss/'
          command: 'mvn clean package'

      - store_artifacts:
          path: './Code/abyss/target/abyss*.jar'
      
      - store_artifacts:
          path: './Code/abyss/target/natives'